import type { StudioModelDefinition } from "./types";

export const STUDIO_MODEL_CATALOG: StudioModelDefinition[] = [
  {
    id: "nano-banana-2",
    name: "Nano Banana 2",
    providerLabel: "Google",
    kind: "image",
    section: "images",
    requestMode: "text-to-image",
    description:
      "Fast still-image generation with the same control surface as the current app page.",
    heroGradient: "from-orange-400/25 via-amber-300/10 to-transparent",
    tags: ["Image", "Featured", "Reference-ready"],
    promptPlaceholder: "Describe the image you want to create...",
    supportsNegativePrompt: false,
    supportsReferences: true,
    maxReferenceFiles: 10,
    acceptedReferenceKinds: ["image"],
    aspectRatioOptions: [
      "1:1",
      "16:9",
      "9:16",
      "4:3",
      "3:4",
      "3:2",
      "2:3",
      "21:9",
      "9:21",
      "auto",
    ],
    resolutionOptions: ["1K", "2K", "4K"],
    outputFormatOptions: ["png", "jpeg", "webp"],
    defaultDraft: {
      prompt: "",
      negativePrompt: "",
      aspectRatio: "1:1",
      resolution: "1K",
      outputFormat: "png",
      imageCount: 1,
      durationSeconds: 6,
      includeAudio: true,
      tone: "Balanced",
      maxTokens: 2048,
      temperature: 0.7,
      voice: "",
      language: "English",
      speakingRate: "1x",
    },
  },
  {
    id: "veo-3.1",
    name: "Veo 3.1",
    providerLabel: "Google",
    kind: "video",
    section: "videos",
    requestMode: "text-to-video",
    description:
      "Narrative video generation with the same duration, ratio, resolution, and audio controls as the current app page.",
    heroGradient: "from-sky-400/25 via-cyan-300/10 to-transparent",
    tags: ["Video", "Featured", "Audio"],
    promptPlaceholder: "Describe the video you want to generate...",
    supportsNegativePrompt: true,
    supportsReferences: true,
    maxReferenceFiles: 3,
    acceptedReferenceKinds: ["image"],
    aspectRatioOptions: ["16:9", "9:16"],
    resolutionOptions: ["720p", "1080p", "4K"],
    durationOptions: [4, 6, 8],
    defaultDraft: {
      prompt: "",
      negativePrompt: "",
      aspectRatio: "16:9",
      resolution: "1080p",
      outputFormat: "mp4",
      imageCount: 1,
      durationSeconds: 6,
      includeAudio: true,
      tone: "Balanced",
      maxTokens: 2048,
      temperature: 0.7,
      voice: "",
      language: "English",
      speakingRate: "1x",
    },
  },
  {
    id: "gemini-flash",
    name: "Gemini 3.0 Flash",
    providerLabel: "Gemini",
    kind: "text",
    section: "text",
    requestMode: "chat",
    description:
      "Fast text and multimodal prompting with the same prompt-first surface as the current app page.",
    heroGradient: "from-indigo-400/25 via-blue-300/10 to-transparent",
    tags: ["Text", "Featured", "Multimodal"],
    promptPlaceholder: "Write your prompt...",
    supportsNegativePrompt: false,
    supportsReferences: true,
    maxReferenceFiles: 10,
    acceptedReferenceKinds: ["image", "video", "audio", "document"],
    defaultDraft: {
      prompt: "",
      negativePrompt: "",
      aspectRatio: "1:1",
      resolution: "",
      outputFormat: "text",
      imageCount: 1,
      durationSeconds: 6,
      includeAudio: false,
      tone: "Balanced",
      maxTokens: 32000,
      temperature: 0.7,
      voice: "",
      language: "English",
      speakingRate: "1x",
    },
  },
  {
    id: "minimax-speech-2.8-hd",
    name: "MiniMax Speech 2.8 HD",
    providerLabel: "MiniMax",
    kind: "audio",
    section: "audio",
    requestMode: "text-to-speech",
    description:
      "High-fidelity text to speech tuned for premium naturalness and clean long-form output.",
    heroGradient: "from-cyan-300/25 via-sky-300/10 to-transparent",
    tags: ["Audio", "Featured", "HD"],
    promptPlaceholder: "Write the narration or speech you want to synthesize...",
    supportsNegativePrompt: false,
    supportsReferences: false,
    outputFormatOptions: ["mp3", "flac"],
    languageOptions: ["English", "Spanish", "French", "Japanese", "Korean"],
    speakingRateOptions: ["0.85x", "1x", "1.15x"],
    defaultDraft: {
      prompt: "",
      negativePrompt: "",
      aspectRatio: "",
      resolution: "",
      outputFormat: "mp3",
      imageCount: 1,
      durationSeconds: 0,
      includeAudio: false,
      tone: "Balanced",
      maxTokens: 4096,
      temperature: 0.7,
      voice: "Wise_Woman",
      language: "English",
      speakingRate: "1x",
    },
  },
  {
    id: "orpheus-tts",
    name: "Orpheus TTS",
    providerLabel: "Canopy",
    kind: "audio",
    section: "audio",
    requestMode: "text-to-speech",
    description:
      "Expressive speech generation designed for more emotive, performance-style voice output.",
    heroGradient: "from-blue-300/25 via-indigo-300/10 to-transparent",
    tags: ["Audio", "Expressive"],
    promptPlaceholder: "Write the spoken script you want voiced...",
    supportsNegativePrompt: false,
    supportsReferences: false,
    outputFormatOptions: ["wav"],
    voiceOptions: [
      "tara",
      "leah",
      "jess",
      "leo",
      "dan",
      "mia",
      "zac",
      "zoe",
    ],
    speakingRateOptions: ["0.9x", "1x", "1.1x"],
    defaultDraft: {
      prompt: "",
      negativePrompt: "",
      aspectRatio: "",
      resolution: "",
      outputFormat: "wav",
      imageCount: 1,
      durationSeconds: 0,
      includeAudio: false,
      tone: "Balanced",
      maxTokens: 4096,
      temperature: 0.7,
      voice: "tara",
      language: "English",
      speakingRate: "1x",
    },
  },
  {
    id: "dia-tts",
    name: "Dia TTS",
    providerLabel: "Nari Labs",
    kind: "audio",
    section: "audio",
    requestMode: "text-to-speech",
    description:
      "Dialogue-friendly speech synthesis with natural pacing for conversational reads and multi-turn delivery.",
    heroGradient: "from-sky-300/25 via-teal-300/10 to-transparent",
    tags: ["Audio", "Dialogue"],
    promptPlaceholder: "Write the dialogue or narration you want voiced...",
    supportsNegativePrompt: false,
    supportsReferences: false,
    outputFormatOptions: ["mp3"],
    languageOptions: ["English"],
    speakingRateOptions: ["0.9x", "1x", "1.1x"],
    defaultDraft: {
      prompt: "",
      negativePrompt: "",
      aspectRatio: "",
      resolution: "",
      outputFormat: "mp3",
      imageCount: 1,
      durationSeconds: 0,
      includeAudio: false,
      tone: "Balanced",
      maxTokens: 4096,
      temperature: 0.7,
      voice: "zero-shot",
      language: "English",
      speakingRate: "1x",
    },
  },
  {
    id: "bria-background-remove",
    name: "Bria Background Remover",
    providerLabel: "Bria",
    kind: "image",
    section: "images",
    requestMode: "background-removal",
    requiresPrompt: false,
    description:
      "Clean background removal that turns a reference image into a transparent cutout PNG.",
    heroGradient: "from-slate-200/20 via-sky-200/10 to-transparent",
    tags: ["Image", "Utility", "Transparent PNG"],
    promptPlaceholder:
      "Drop or upload an image to remove the background. Optional note here.",
    supportsNegativePrompt: false,
    supportsReferences: true,
    minimumReferenceFiles: 1,
    maxReferenceFiles: 1,
    acceptedReferenceKinds: ["image"],
    outputFormatOptions: ["png"],
    defaultDraft: {
      prompt: "",
      negativePrompt: "",
      aspectRatio: "",
      resolution: "",
      outputFormat: "png",
      imageCount: 1,
      durationSeconds: 0,
      includeAudio: false,
      tone: "Balanced",
      maxTokens: 2048,
      temperature: 0.7,
      voice: "",
      language: "English",
      speakingRate: "1x",
    },
  },
];

export const STUDIO_MODEL_SECTIONS = [
  {
    id: "images",
    title: "Images",
    description: "Image generation models",
  },
  {
    id: "videos",
    title: "Videos",
    description: "Video generation models",
  },
  {
    id: "text",
    title: "Text",
    description: "LLM text and multimodal models",
  },
  {
    id: "audio",
    title: "Audio",
    description: "Text-to-speech models",
  },
] as const;

export function getStudioModelById(modelId: string) {
  return (
    STUDIO_MODEL_CATALOG.find((model) => model.id === modelId) ??
    STUDIO_MODEL_CATALOG[0]
  );
}
